export const cwrWorkType = {
  TA: "AAA (Triple A)",
  AC: "Adult Contemporary",
  AR: "Album Oriented Rock (AOR)",
  AL: "Alternative Music",
  AM: "Americana",
  BD: "Band",
  BL: "Bluegrass Music",
  CD: "Children’s Music",
  CL: "Classical Music",
  CC: "Contemporary Christian",
  CT: "Country Music",
  DN: "Dance",
  FM: "Film/ Television Music",
  FK: "Folk Music",
  BG: "Gospel (Black)",
  SG: "Gospel (Southern)",
  JZ: "Jazz Music",
  JG: "Jingles",
  LN: "Latin",
  LA: "Latina",
  NA: "New Age",
  OP: "Opera",
  PK: "Polka Music",
  PP: "Pop Music",
  RP: "Rap Music",
  RK: "Rock Music",
  RB: "Rhythm and Blues",
  SD: "Sacred",
  SY: "Symphonic",
};
