export const Instruments = {
  ACC: "Accordion",
  ALP: "Alp Horn",
  ACL: "Alto Clarinet",
  AFL: "Alto Flute",
  AHN: "Alto Horn",
  ARC: "Alto Recorder",
  ASX: "Alto Saxophone",
  ALT: "Alto Voice",
  AMP: "Amplifier",
  BAG: "Bagpipes",
  BKA: "Balalaika",
  BBF: "Bamboo Flute",
  BDN: "Bandoneon",
  BNJ: "Banjo",
  BAR: "Baritone Horn",
  BSX: "Baritone Saxophone",
  BTN: "Baritone Voice",
  BQF: "Baroque Flute",
  BBT: "Bass Baritone",
  BCL: "Bass Clarinet",
  BDR: "Bass Drum",
  BFT: "Bass Flute",
  BGT: "Bass Guitar",
  BOB: "Bass Oboe",
  BRC: "Bass Recorder",
  BSP: "Bass Saxophone",
  BRT: "Bass Trombone",
  BSS: "Bass Voice",
  BHN: "Basset Horn",
  BSN: "Bassoon",
  BEL: "Bells",
  BNG: "Bongos",
  BOY: "Boy Soprano",
  BGL: "Bugle",
  CAR: "Carillon",
  CST: "Castanets",
  CEL: "Celesta",
  CHM: "Chimes",
  CIM: "Cimbalom",
  CLR: "Clarinet",
  CVD: "Clavichord",
  COM: "Computer",
  CNB: "Concertina",
  CNG: "Congas",
  CBN: "Contra Bassoon",
  CBC: "Contrabass Clarinet",
  CCL: "Contralto Clarinet",
  CAL: "Contralto Voice",
  CNT: "Cornet",
  CTN: "Countertenor Voice",
  CYM: "Cymbals",
  DIJ: "Didjeridu",
  DIZ: "Dizi/D'Tzu",
  DJM: "Djembe",
  BAS: "Double Bass",
  DRM: "Drum",
  DRK: "Drum Kit/Drum Set",
  DUL: "Dulcimer",
  EFC: "E-Flat Clarinet",
  EBG: "Electric Bass Guitar",
  EGT: "Electric Guitar",
  EOG: "Electronic Organ",
  ELL: "Electronics, Live",
  ELP: "Electronics, Pre-recorded",
  EHN: "English Horn",
  ERH: "Erhu",
  EUP: "Euphonium",
  FLG: "Flugelhorn",
  FLT: "Flute",
  FRN: "French Horn",
  GHM: "Glass Harmonica",
  GHP: "Glass Harp",
  GLS: "Glockenspiel",
  GNG: "Gong",
  GTR: "Guitar",
  HBL: "Handbells",
  HAR: "Harmonica",
  HRM: "Harmonium",
  HRP: "Harp",
  HPS: "Harpsichord",
  HCK: "Heckelphone",
  HRN: "Horn",
  HUR: "Hurdy-Gurdy",
  KAZ: "Kazoo",
  KEY: "Keyboard",
  KLV: "Klavier",
  KOT: "Koto",
  LUT: "Lute",
  LYR: "Lyre",
  MAN: "Mandolin",
  MCS: "Maracas",
  MAR: "Marimba",
  MBR: "Mbira",
  MEL: "Melodica",
  MEZ: "Mezzo Soprano Voice",
  MID: "Midi",
  MSB: "Music Box",
  NAR: "Narrator/Speaker",
  NAF: "Native American Flute",
  NHN: "Natural Horn",
  OBO: "Oboe",
  OBD: "Oboe d'Amore",
  OND: "Ondes Martinot",
  ORG: "Organ",
  PWH: "Pennywhistle",
  PER: "Percussion",
  PIA: "Piano",
  PIC: "Piccolo",
  PPA: "Pipa",
  PRP: "Prepared Piano",
  PRO: "Processor",
  REC: "Recorder",
  RUA: "Ruan",
  SAM: "Sampler",
  SAX: "Saxophone",
  SEQ: "Sequencer",
  SHK: "Shakuhachi",
  SHM: "Shamisen",
  SHW: "Shawm",
  SHO: "Sho",
  SIT: "Sitar",
  SDM: "Snare drum",
  SNR: "Sopranino Recorder",
  SNS: "Sopranino Saxophone",
  SRC: "Soprano Recorder",
  SSX: "Soprano Saxophone",
  SOP: "Soprano Voice",
  SOU: "Sousaphone",
  SPO: "Spoons",
  STD: "Steel drums",
  SYN: "Synthesizer",
  TAB: "Tabla",
  TAM: "Tambour",
  TMN: "Tambourine",
  TTM: "Tamtam",
  TAP: "Tape",
  THN: "Tenor Horn",
  TRC: "Tenor Recorder",
  TSX: "Tenor Saxophone",
  TEN: "Tenor Voice",
  THE: "Theremin",
  TIM: "Timpani",
  TYP: "Toy Piano",
  TRI: "Triangle",
  TMB: "Trombone",
  TRM: "Trumpet",
  TBA: "Tuba",
  UKE: "Ukulele",
  VIB: "Vibraphone",
  VID: "Video",
  VLA: "Viola",
  VDG: "Viola Da Gamba",
  VLN: "Violin",
  VCL: "Violoncello",
  VOC: "Voice",
  WTB: "Wagner Tuba",
  WHS: "Whistle",
  WBK: "Wood block",
  XYL: "Xylophone",
  YQN: "Yang Qin",
  ZHG: "Zheng",
  ZIT: "Zither",
};
