export const standardInstrumentation = {
  AUD: "Audience",
  BND: "Band",
  BBA: "Brass Band",
  BRC: "Brass Choir",
  BQU: "Brass Quartet",
  BQN: "Brass Quintet",
  BXT: "Brass Sextet",
  BTR: "Brass Trio",
  CEN: "Chamber Ensemble",
  CHO: "Chorus",
  CAO: "Chorus and Orchestra",
  BCH: "Chorus, Boys’",
  CCH: "Chorus, Children’s",
  DCH: "Chorus, Double",
  MCH: "Chorus, Men’s",
  MXC: "Chorus, Mixed",
  TCH: "Chorus, Treble",
  UCH: "Chorus, Unison",
  WCH: "Chorus, Women's",
  YCH: "Chorus, Youth",
  CLC: "Clarinet Choir",
  CQN: "Clarinet Quintet",
  CBA: "Concert Band",
  FLC: "Flute Choir",
  GML: "Gamelan",
  GQT: "Guitar Quartet",
  HNC: "Horn Choir",
  JZE: "Jazz Ensemble",
  OQU: "Oboe Quartet",
  COR: "Orchestra, Chamber",
  ORC: "Orchestra, Full",
  SOR: "Orchestra, String",
  PCE: "Percussion Ensemble",
  PDU: "Piano Duo",
  PFH: "Piano Four Hands",
  PQU: "Piano Quartet",
  PQN: "Piano Quintet",
  PTR: "Piano Trio",
  SQT: "Saxophone Quartet",
  SOC: "String Octet",
  SQU: "String Quartet",
  SQN: "String Quintet",
  SGT: "String Trio",
  SBA: "Symphonic Band",
  TBC: "Trombone Choir",
  TPC: "Trumpet Choir",
  TUC: "Tuba Choir",
  WEN: "Wind Ensemble",
  WQR: "Woodwind Quartet",
  WQN: "Woodwind Quintet",
};
